title: My awesome blog
author: Saibot
email: saibot@fn.de
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is not an awesome description for your my blog.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
